### ISSUE TITLE
Create a list with project names

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/diy-project-planner#1]
# Value Proposition

**As a** user
**I want to** add projects to a list
**So that** I have an overview about my current projects

# Description

![Image](https://user-images.githubusercontent.com/107792731/190894974-e5052d51-0b05-4749-bc3a-704afbe0a4e6.png)

![Image](https://user-images.githubusercontent.com/107792731/190895052-bf0f8cd4-92ce-4e56-9c2c-f32f86d5fc01.png)

# Acceptance Criteria

- [x] there is an input field
- [x] there is a submit button
- [x] when the button is clicked, projects are added to a list on the projects page

# Tasks

- [x] create a new branch
- [x] create a styled component for the input field
- [x] create a styled component for the submit button
- [x] create a styled component for the items of the project list
- [x] create a projects page
- [x] put the input field & submit button on the projects page
- [x] map the project items on the project page

# Complexity

M
